package org.usfirst.frc5858.SteamworksBot.commands;

import org.usfirst.frc5858.SteamworksBot.Robot;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class LoanerMove extends Command {

	@Override
	protected boolean isFinished() {
		// TODO Auto-generated method stub
		return false;
	}
	public LoanerMove() {

	    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

	        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
	        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	        requires(Robot.drivetrain);

	        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	    }
	protected void execute() {
    	Joystick j = new Joystick(0);
    	double x = j.getX();
    	double y = j.getY();
    	double rotation = j.getTwist();
    	
    	//if(x>-0.5 && x<0.5) x=0.0;
    	//if(y>-0.5 && y<0.5) y=0.0;
    	
    	SmartDashboard.putString("topher", "x="+x+" y="+y); 
    	
    	
    	Robot.drivetrain.LoanerDrive(x, y, rotation);
    	
	}
}
