// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5858.SteamworksBot.subsystems;

import org.usfirst.frc5858.SteamworksBot.RobotMap;
import org.usfirst.frc5858.SteamworksBot.commands.*;

//import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//    private final CANTalon frontLeft = RobotMap.drivetrainfrontLeft;
//    private final CANTalon frontRIght = RobotMap.drivetrainfrontRIght;
//    private final CANTalon backLeft = RobotMap.drivetrainbackLeft;
//    private final CANTalon backRight = RobotMap.drivetrainbackRight;
//    private final ADXRS450_Gyro robotGyro = RobotMap.drivetrainrobotGyro;
//    private final Encoder driveEncoder = RobotMap.drivetraindriveEncoder;
    
    //private final RobotDrive robotDrive = RobotMap.drivetrainRobotDrive;
    
    private final RobotDrive LoanerDrive = RobotMap.loanerRobotDrive;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Joystick joystick = new Joystick(0);
  
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
       setDefaultCommand(new LoanerMove());
    }

    public void FieldCentricDrive(double x, double y, double rotation, double gyroAngle)
    {
    	//robotDrive.mecanumDrive_Cartesian(x, y, rotation, gyroAngle);
    }

    public void Drive(double x, double y, double rotation) {
    	//robotDrive.mecanumDrive_Cartesian(x, y, rotation, 0.0);
    }
    
   // this is the loaner stuff 
    public void LoanerDrive(double x, double y, double rotation) {
    	LoanerDrive.mecanumDrive_Cartesian(x, y, rotation, 0.0);
    }
    
    public void LoanerStop()    {
    	LoanerDrive.mecanumDrive_Cartesian(0, 0, 0, 0);	
    }
    
    public void GoToAngle(double angle)
    {
    	// do stuff ?
    	// read acceleometere
    	// am i facing correct degrees yet?
    	// if yes:  stop
    	// if no:   keep going!
	// this probably should be a command rather than a part of drivetrain
	// since it may take time and block...
    }
    
    

}


