// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5858.SteamworksBot.subsystems;

import org.usfirst.frc5858.SteamworksBot.RobotMap;
import org.usfirst.frc5858.SteamworksBot.commands.CameraDown;
import org.usfirst.frc5858.SteamworksBot.commands.CarmeraHatMove;
import org.usfirst.frc5858.SteamworksBot.commands.LoanerMove;

import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class VisionCamera extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Servo cameraServoX = RobotMap.visionCameracameraServoX;
    private final Servo cameraServoY = RobotMap.visionCameracameraServoY;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    	setDefaultCommand(new CarmeraHatMove());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    
    // double x -.5(left) to .5(right) 
    public void setX(double x){
    	double cmd=x+0.5;
        cameraServoX.set(cmd);

    }

 // double y -.5(down) to .5(up)
    public void setY(double y){
    	double cmd=y+0.5;
        cameraServoY.set(cmd);

    }
    // double x -.5(left) to .5(right)
    public void set(double x, double y){
        setX(x);
        setY(y);
    }
    
}

