// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5858.SteamworksBot.commands;

import java.util.LinkedList;
import java.util.List;

import org.usfirst.frc5858.SteamworksBot.Robot;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class AutoPutGearOnPeg extends Command {
	
	private List<Double> ultrasonicValues=new LinkedList<Double>();
	private boolean done = false;
	
	public AutoPutGearOnPeg() {
		requires(Robot.drivetrain);
	  	requires(Robot.visionCamera);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		int err = Robot.visionCamera.getError();
		double range = GetSmoothRange();
		SmartDashboard.putString("DB/String 5", "Range: " + (int) range);
		
		double x = 0.0;
		double y = 0.0;
		
		if (err > 10) {
			x = 0.1;
		}
		else if (err < -10) {
			x = -0.1;
		}
		else if (range > 7) {
			y = 0.1;
		} else {
			done = true;
		}
		
		Robot.drivetrain.Drive(x, y, 0.0);
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return done;
	}

	protected double GetSmoothRange(){
		double range=Robot.drivetrain.GetRange();
		ultrasonicValues.add(range);
		if (ultrasonicValues.size() > 15) {
			ultrasonicValues.remove(0);
		}
		double sum = 0;
		for (Double value: ultrasonicValues) {
			sum+= value;
		}
		return sum / ultrasonicValues.size();
	}
}
